field.widget.settings.hel_tpm_editorial_paragraphs_accessibility:
  type: field.widget.settings.paragraphs
  label: 'Paragraphs Accessibility widget settings'
  mapping:
    add_label:
      type: label
      label: 'Override add label'
