#!/bin/bash

TOP=$(git rev-parse --show-toplevel)

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- "$TOP/public/themes/custom" \
| grep -Ev '/(dist|build)/')

if [[ -z "$STAGED_FILES" ]]; then
  exit 0
fi

PASS=true

run_tool() {
  if ddev describe >/dev/null 2>&1; then
    ddev "$@"
  elif lando info >/dev/null 2>&1; then
    lando "$@"
  elif [[ -f "$TOP/.ddev/config.yaml" ]]; then
    ddev "$@"
  elif [[ -f "$TOP/.lando.yml" ]]; then
    lando "$@"
  else
    echo "ERROR: No DDEV or Lando environment detected."
    exit 1
  fi
}

echo "Checking theme file Drupal coding standards"

for FILE in $STAGED_FILES
do
  run_tool phpcs "$FILE"

  if [[ $? -ne 0 ]]; then
    echo "PHPCS Failed: $FILE"
    PASS=false
  fi
done

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that do not pass Drupal coding standards."
  echo "Please fix the PHPCS errors and try again."
  exit 1
fi

echo "Checking theme Drupal best practices"

for FILE in $STAGED_FILES
do
  run_tool phpcsp "$FILE"

  if [[ $? -ne 0 ]]; then
    echo "PHPCSP Failed: $FILE"
    PASS=false
  fi
done

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass syntax checks but do not. Please fix the Drupal best practice errors and try again.\n"
  exit 1
fi

exit 0
