#!/bin/sh

TOP=$(git rev-parse --show-toplevel);
LANDO_ROOT="/app"
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- "$TOP/public/themes/custom")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo "Checking theme file Drupal coding standards"
for FILE in $STAGED_FILES
do
  lando phpcs "$LANDO_ROOT/$FILE";
  if [[ "$?" != 0 ]]; then
    echo "PHPCS Failed: $FILE"
    PASS=false
  fi
done

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass syntax checks but do not. Please fix the PHPCS errors and try again.\n"
  exit 1
fi

echo "Checking theme Drupal best practices"
for FILE in $STAGED_FILES
do
  lando phpcsp "$LANDO_ROOT/$FILE";

  if [[ "$?" != 0 ]]; then
    echo "PHPCSP Failed: $FILE"
    PASS=false
  fi
done

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass syntax checks but do not. Please fix the Drupal best practice errors and try again.\n"
  exit 1
fi