#!/bin/bash

TOP=$(git rev-parse --show-toplevel)

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- "$TOP/public/modules/custom")

if [[ -z "$STAGED_FILES" ]]; then
  exit 0
fi

PASS=true

run_tool() {
  if ddev describe >/dev/null 2>&1; then
    ddev "$@"
  elif lando info >/dev/null 2>&1; then
    lando "$@"
  else
    echo "No running DDEV or Lando environment found."
    exit 1
  fi
}

echo "Checking Drupal coding standards"

for FILE in $STAGED_FILES
do
  run_tool phpcs "$FILE"

  if [[ $? -ne 0 ]]; then
    echo "PHPCS Failed: $FILE"
    PASS=false
  fi
done

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass syntax checks but do not. Please fix the PHPCS errors and try again.\n"
  exit 1
fi

echo "Checking Drupal best practices"

for FILE in $STAGED_FILES
do
  run_tool phpcsp "$FILE"

  if [[ $? -ne 0 ]]; then
    echo "PHPCSP Failed: $FILE"
    PASS=false
  fi
done

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass syntax checks but do not. Please fix the Drupal best practice errors and try again.\n"
  exit 1
fi

exit 0
