name: helfi-manuska
recipe: drupal8
config:
  via: nginx
  webroot: public
  php: "8.1"
  database: mariadb:10.3
  composer_version: 2
proxy:
  mailhog:
    - mail.helfimanuska.lndo.site
  search:
    - admin.solr.lndo.site:8983
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  redis:
    type: redis
  appserver:
    xdebug: true
    build:
      - "/app/vendor/bin/phpcs --config-set installed_paths /app/coder/vendor/drupal/coder/coder_sniffer"
    config:
      php: .lando.php.ini
    overrides:
      environment:
        ENVIRONMENT: "local"
        PHP_IDE_CONFIG: "serverName=appserver"
        SIMPLETEST_BASE_URL: "http://helfi-manuska.lndo.site"
        SIMPLETEST_DB: "mysql://drupal8:drupal8@database/drupal8"
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
        DRUSH_OPTIONS_URI: "https://helfi-manuska.lndo.site"
        TFA_KEY: ''
  chrome:
    type: compose
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips=
  elastic:
    type: elasticsearch:7
    portforward: true
    mem: 1025m
  solr:
    type: solr:8
    core: solr
    portforward: true
    config:
      dir: ./.solr/core
tooling:
  # Create additional commands for lando
  install-drupal:
    service: appserver
    description: Run Citrus specific Drupal 8 installation script
    cmd: /app/scripts/citrus/install-drupal-lando.sh
  create-drupal-theme:
    service: appserver
    description: Create Drupal 8 theme for current environment
    cmd: /app/scripts/citrus/create-drupal-theme-lando.sh
  test:
    service: appserver
    cmd: "php /app/vendor/bin/phpunit -c /app/phpunit.xml /app/public/modules/custom"
  test-cs:
    service: appserver
    description: Run Drupal 8 tests
    cmd:
      - /app/vendor/bin/phpcs --standard=Drupal,DrupalPractice -n --report=full  public/modules/custom
#      - /app/vendor/bin/behat --config=/app/tests/behat-lando.yml
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd: /var/www/.platformsh/bin/platform
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat --config=/app/tests/behat-lando.yml
