<?php
namespace Drupal\hel_tpm_group\Plugin\Field\FieldWidget;

use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\select2\Plugin\Field\FieldWidget\Select2EntityReferenceWidget;
use Drupal\select2\Select2Trait;

/**
 * Plugin implementation of the 'hel_tpm_group_user_select_widget' widget.
 *
 * @FieldWidget(
 *   id = "hel_tpm_group_select2_widget",
 *   label = @Translation("Hel Group Select2"),
 *   field_types = {
 *     "entity_reference"
 *   },
 *   multiple_values = TRUE
 * )
 */
class GroupSelect2Widget extends Select2EntityReferenceWidget {

  use Select2Trait;

  /**
   * @param \Drupal\Core\Field\FieldItemListInterface $items
   * @param $delta
   * @param array $element
   * @param array $form
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *
   * @return array
   */
  public function formElement(FieldItemListInterface $items, $delta, array $element, array &$form, FormStateInterface $form_state): array {
    $element =  parent::formElement($items, $delta, $element, $form, $form_state); // TODO: Change the autogenerated stub
    $options = $element['#options'];

    // If there's more than one option available don't set default value.
    if (count($options) > 1) {
      return $element;
    }

    // If default value is not empty return element.
    if (!empty($element['#default_value'])) {
      return $element;
    }
    // Set default value for field.
    $element['#default_value'] = array_key_first($options);

    return $element;
  }

}
