<?php

namespace Drupal\Tests\hel_tpm_group\Kernel;

use Drupal\KernelTests\KernelTestBase;
use Drupal\user\Entity\Role;

/**
 * Tests hel_tpm_group.module helper functions.
 *
 * @group hel_tpm_group
 */
class HelTpmGroupModuleTest extends KernelTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = [
    'system',
    'user',
    'options',
    'entity',
    'flexible_permissions',
    'group',
    'ggroup',
    'message',
    'message_notify',
    'hel_tpm_mail_tools',
    'hel_tpm_group',
  ];

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    // @todo Change the autogenerated stub.
    parent::setUp();
    $this->installEntitySchema('user');
    $this->installConfig('user');
  }

  /**
   * Tests that _hel_tpm_group_user_roles() returns non-anonymous role labels.
   */
  public function testHelTpmGroupUserRoles(): void {
    Role::create([
      'id' => 'editor',
      'label' => 'Editor',
    ])->save();

    Role::create([
      'id' => 'publisher',
      'label' => 'Publisher',
    ])->save();

    $roles = _hel_tpm_group_user_roles();

    $this->assertContains('Authenticated user', $roles);
    $this->assertContains('Editor', $roles);
    $this->assertContains('Publisher', $roles);
    $this->assertNotContains('Anonymous user', $roles);
  }

  /**
   * Tests that _hel_tpm_group_get_valid_roles() returns allowed role labels.
   */
  public function testHelTpmGroupGetValidRoles(): void {
    Role::create([
      'id' => 'editor',
      'label' => 'Editor',
    ])->save();

    Role::create([
      'id' => 'publisher',
      'label' => 'Publisher',
    ])->save();

    Role::create([
      'id' => 'root',
      'label' => 'Root',
    ])->save();

    Role::create([
      'id' => 'admin',
      'label' => 'Admin',
    ])->save();

    $roles = _hel_tpm_group_get_valid_roles();

    $this->assertContains('Editor', $roles);
    $this->assertContains('Publisher', $roles);
    $this->assertNotContains('Authenticated user', $roles);
    $this->assertNotContains('Root', $roles);
    $this->assertNotContains('Admin', $roles);
    $this->assertNotContains('Anonymous user', $roles);
  }

}
