<?php

/**
 * @file
 * Primary module hooks for Hel Tpm Subgroup module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_group_content_info_alter().
 */
function hel_tpm_subgroup_group_content_info_alter(array &$groupContentInfo) {
  // Inject our custom Access Control Handler (ACH) to allow our custom
  // "visibility" field on nodes to open-up access to syllabi and
  // resources when the instructor chooses "Everyone at the School" or
  // "Public / Anyone in the world" as the visibility.
  //
  // Without this, Group 1.3's GroupContentAccessControlHandler now returns an
  // AccessResult::forbidden() result if the content is in a group (as all
  // syllabi and resources are).
  //
  // To ensure that we aren't accidentally exposing content that doesn't have a
  // visibility field, we'll look for the presence of that field on the target
  // entity-type.
  foreach ($groupContentInfo as &$info) {
    // Use our custom ACH to expose group-content more publicly if the target
    // bundle has our custom visibility field.
    if ($info['entity_type_id'] == 'group' && $info['id'] == 'subgroup') {
      $info['handlers']['access'] = 'Drupal\hel_tpm_subgroup\Plugin\SubgroupGroupAccessControlHandler';
    }
  }
}
