<?php

/**
 * @file
 * Module file for hel_tpm_url_shortener.
 */

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_cron().
 */
function hel_tpm_url_shortener_cron() {
  _hel_tpm_url_shortener_garbage_collection();
}

/**
 * Executes the garbage collection process for the URL shortener service.
 *
 * This function ensures the garbage collection process for
 * the hel_tpm_url_shortener is not executed more frequently than once per day.
 * It checks the last execution time stored in the state system and proceeds
 * with garbage collection if the last run was more than 24 hours ago.
 *
 * @return void
 *   No return value. Executes garbage collection and updates the last run time.
 */
function _hel_tpm_url_shortener_garbage_collection() {
  $last_run_state = 'hel_tpm_url_shortener_garbage_collector_last_run';
  $last_run = \Drupal::state()->get($last_run_state);
  $limit = new DrupalDateTime('-1 day');

  if ($last_run >= $limit->getTimestamp()) {
    return;
  }

  \Drupal::service('hel_tpm_url_shortener.garbage_collector')->collect();
  \Drupal::state()->set($last_run_state, \Drupal::time()->getCurrentTime());
}

/**
 * Implements hook_form_alter().
 */
function hel_tpm_url_shortener_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'views_exposed_form' && in_array('views_exposed_form__solr_service_search__page', $form['#theme'])) {
    $short_link_form = \Drupal::formBuilder()->getForm('Drupal\hel_tpm_url_shortener\Form\ShortenUrlLinkFormViews');
    if (\Drupal::currentUser()->isAuthenticated()) {
      $form['short_url_form'] = $short_link_form['wrapper'];
    }
  }
}
