<?php

namespace Drupal\service_manual_workflow\Form;

use Drupal\Core\Entity\EntityTypeManager;
use Drupal\Core\Form\ConfirmFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\service_manual_workflow\Access\ServiceOutdatedAccess;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Confirmation form for set service outdated operation.
 */
class SetServiceOutdatedOperationForm extends ConfirmFormBase {

  /**
   * Entity type manager service.
   *
   * @var \Drupal\Core\Entity\EntityTypeManager
   */
  protected $entityTypeManager;

  /**
   * Service outdated access service.
   *
   * @var \Drupal\service_manual_workflow\Access\ServiceOutdatedAccess
   */
  protected $serviceOutdatedAccess;

  /**
   * {@inheritdoc}
   */
  public function __construct(EntityTypeManager $entity_type_manager, ServiceOutdatedAccess $service_outdated_access) {
    $this->entityTypeManager = $entity_type_manager;
    $this->serviceOutdatedAccess = $service_outdated_access;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('entity_type.manager'),
      $container->get('service_manual_workflow.set_outdated_access')
    );
  }

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return $this->t('Confirm changing @node to Outdated', ['@node' => $this->node->getTitle()]);
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return $this->t('Are you sure you want to change @node as Outdated and unpublish it?', [
      '@node' => $this->node->getTitle(),
    ]);
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'service_workflow_set_outdated_operation_confirm';
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $node = $this->node;
    // Only current language is set as outdated.
    if (!$form_state->getValue('all_translations_outdated')) {
      $this->setNodeOutdated($node);
      return;
    }

    foreach ($node->getTranslationLanguages() as $id => $language) {
      $translation = $node->getTranslation($id);
      $this->setNodeOutdated($translation);
    }
  }

  /**
   * Set node outdated method.
   *
   * @param \Drupal\node\NodeInterface $node
   *   Node object.
   *
   * @return void
   *   -
   *
   * @throws \Drupal\Core\Entity\EntityStorageException
   */
  protected function setNodeOutdated(NodeInterface $node) {
    $node->set('moderation_state', 'outdated');
    $node->save();
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, $node = NULL) {
    if (!$node instanceof NodeInterface) {
      return [];
    }
    $this->node = $node;
    // @todo Change the autogenerated stub.
    $form = parent::buildForm($form, $form_state);
    $form['all_translations_outdated'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('Set all translations as outdated'),
    ];
    return $form;
  }

  /**
   * Access method to check if user has access to node.
   *
   * @param \Drupal\node\NodeInterface $node
   *   Node object.
   *
   * @return \Drupal\Core\Access\AccessResultAllowed|\Drupal\Core\Access\AccessResultForbidden
   *   Returns access result object.
   */
  public function access(NodeInterface $node) {
    return $this->serviceOutdatedAccess->access($node, $this->currentUser());
  }

}
