<?php
namespace Drupal\service_manual_workflow\Form;

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityTypeManager;
use Drupal\Core\Form\ConfirmFormBase;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\service_manual_workflow\Access\ServiceOutdatedAccess;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Routing\RouterInterface;

class SetServiceOutdatedOperationForm extends ConfirmFormBase {

  /**
   * @var \Drupal\Core\Entity\EntityTypeManager
   */
  protected $entityTypeManager;

  /**
   * @var \Drupal\service_manual_workflow\Access\ServiceOutdatedAccess
   */
  protected $serviceOutdatedAccess;

  public function __construct(EntityTypeManager $entity_type_manager, ServiceOutdatedAccess $service_outdated_access) {
    $this->entityTypeManager = $entity_type_manager;
    $this->serviceOutdatedAccess = $service_outdated_access;
  }

  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('entity_type.manager'),
      $container->get('service_manual_workflow.set_outdated_access')
    );
  }

  public function getQuestion() {
    return $this->t('Confirm changing @node to Outdated', ['@node' => $this->node->getTitle()]);
  }

  public function getDescription() {
    return $this->t('Are you sure you want to change @node as Outdated and unpublish it?', [
      '@node' => $this->node->getTitle()
    ]);
  }

  public function getCancelUrl() {
    return parent::getCancelUrl();
  }

  public function getFormId() {
    return 'service_workflow_set_outdated_operation_confirm';
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $node = $this->node;
    // Only current language is set as outdated.
    if (!$form_state->getValue('all_translations_outdated')) {
      $this->setNodeOutdated($node);
      return;
    }

    foreach ($node->getTranslationLanguages() as $id => $language) {
      $translation = $node->getTranslation($id);
      $this->setNodeOutdated($translation);
    }
  }

  protected function setNodeOutdated(NodeInterface $node) {
    $node->set('moderation_state', 'outdated');
    $node->save();
  }

  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function buildForm(array $form, FormStateInterface $form_state, $node = NULL) {
    if (!$node instanceof NodeInterface) {
      return [];
    }
    $this->node = $node;
    $form = parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
    $form['all_translations_outdated'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('Set all translations as outdated')
    ];
    return $form;
  }

  /**
   * @param \Drupal\node\NodeInterface $node
   *
   * @return \Drupal\Core\Access\AccessResultAllowed|\Drupal\Core\Access\AccessResultForbidden
   */
  public function access(NodeInterface $node) {
    return $this->serviceOutdatedAccess->access($node, $this->currentUser());
  }
}