<?php

/**
 * @file
 * Module file for hel_tpm_search_autosuggest.
 */

/**
 * Implements hook_theme().
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function hel_tpm_search_autosuggest_theme() {
  $themes['hel_tpm_search_autocomplete'] = [
    'variables' => [],
  ];
  return $themes;
}

/**
 * Implements hook_form_alter().
 */
function hel_tpm_search_autosuggest_form_alter(&$form, FormStateInterface $form_state) {
  $storage = $form_state->getStorage();
  if (empty($storage['view']) ||
    $storage['view']->id() != 'solr_service_search' ||
    $form['#form_id'] !== 'views_exposed_form') {
    return;
  }

  $form['search_wrapper'] = [
    '#type' => 'container',
    '#attributes' => ['class' => 'search-autocomplete-wrapper'],
  ];

  $form['search_api_fulltext'] = [
    '#type' => 'textfield',
    '#id' => 'hel-tpm-search-autocomplete',
    '#attributes' => [
      'placeholder' => t('Search from all services'),
      'autocomplete' => 'off',
    ],
    '#attached' => ['library' => ['hel_tpm_search_autosuggest/hel_tpm_search_autosuggest']],
    '#default_value' => \Drupal::request()->query->get('search_api_fulltext'),
  ];
  $form['search_wrapper']['list_items'] = [
    '#theme' => 'hel_tpm_search_autocomplete',
  ];
  $form['search_wrapper']['search_api_fulltext'] = $form['search_api_fulltext'];

  $form['actions']['submit']['#attributes']['title'] = t('Search from all services');

  // Generate weights for fields.
  _hel_tpm_search_autosuggest_reweight_fields($form, $storage['view']);

  // Remove original search_api_fulltext field.
  unset($form['search_api_fulltext']);

  // Disabled search_api_autocomplete callbacks.
  $form['#process'] = [];

  return $form;
}

/**
 * Helper function to generate weights for exposed filter fields.
 *
 * @param array $form
 *   Form render array.
 * @param \Drupal\views\ViewExecutable $view
 *   View where field is used in.
 *
 * @return void
 *   -
 */
function _hel_tpm_search_autosuggest_reweight_fields(&$form, ViewExecutable $view) {
  $i = 0;
  // Re-weight the fields to match proper placement.
  foreach ($view->filter as $field_key => $filter) {
    if (!$filter->isExposed()) {
      continue;
    }
    if ($field_key == 'search_api_fulltext') {
      $field_key = 'search_wrapper';
    }
    $form[$field_key]['#weight'] = $i;
    $i++;
  }
  $form['sort_by']['#weight'] = $i;
}
