<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 *
 * @param $fields
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 *
 * @return void
 */
function hel_tpm_editorial_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'notification_message') {
    $fields['publish_end_date']->addConstraint('NotificationMessageExpiry');
  }
}

/**
 * Implements hook_form_views_exposed_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 *
 * @return void
 */
function hel_tpm_editorial_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $view = $form_state->getStorage()['view'];
  if (isset($form['moderation_state']) && $view->id() == "service_search") {
    $form['moderation_state']['#type'] = 'select';
    $form['moderation_state']['#options'] = [
      'published' => t('Published'),
      'on_hold' => t('On hold'),
    ];
    unset($form['moderation_state']['#size']);
  }
}

/**
 * Implements hook_theme().
 *
 * @return array[]
 */
function hel_tpm_editorial_theme() {
  return [
    'multistep_navigation' => [
      'template' => 'multistep_navigation',
      'variables' => [
        'navigation' => NULL,
      ],
    ],
    'hel_tpm_editorial_date_recur_custom_widget' => [
      'render element' => 'widget',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * HOOK: 'date_recur_modular_widget'.
 */
function template_preprocess_hel_tpm_editorial_date_recur_custom_widget(array &$variables): void {
  $variables['attributes']['class'][] = 'hel-tpm-editorial-date-recur-custom-widget';
  $variables['#attached']['library'][] = 'date_recur_modular/date_recur_modular_alpha_widget';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the node form.
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 *
 * @return void
 */
function hel_tpm_editorial_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  $bundle = $form_state->getStorage()['form_display']->getTargetBundle();
  if ($bundle == 'service') {
    $form['revision_log']['#access'] = FALSE;
    $form['created']['#access'] = FALSE;
    $form['uid']['#access'] = FALSE;
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * @param $implementations
 * @param $hook
 *
 * @return void
 */
function hel_tpm_editorial_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if (isset($implementations['hel_tpm_editorial'])) {
      $group = $implementations['hel_tpm_editorial'];
      unset($implementations['hel_tpm_editorial']);
      $implementations['hel_tpm_editorial'] = $group;
    }
  }
}
