<?php

use Drupal\Core\Entity\EntityTypeInterface;

function hel_tpm_editorial_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'notification_message') {
    $fields['publish_end_date']->addConstraint('NotificationMessageExpiry');
  }
}

function hel_tpm_editorial_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (isset($form['moderation_state'])) {
    $form['moderation_state']['#type'] = 'select';
    $form['moderation_state']['#options'] = [
      'published' => t('Published'),
      'on_hold' => t('On hold'),
    ];
    unset($form['moderation_state']['#size']);
  }
}

/**
 * Implements hook_theme().
 *
 * @return array[]
 */
function hel_tpm_editorial_theme() {
  return [
    'multistep_navigation' => [
      'template' => 'multistep_navigation',
      'variables' => [
        'navigation' => NULL,
      ],
    ]
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 *
 * @return void
 */
function hel_tpm_editorial_form_node_service_edit_form_alter(&$form, &$form_state, $form_id) {
  $form['paging_header'] = [
    '#theme' => 'multistep_navigation',
    '#navigation' => _hel_tpm_editorial_node_pager_navigation($form, $form_state)
  ];
}

/**
 * Helper function to build renderable array for navigation.
 *
 * @param $form
 * @param $form_state
 *
 * @return array|false
 */
function _hel_tpm_editorial_node_pager_navigation($form, $form_state) {
  $storage = $form_state->getStorage();
  if (empty($storage['field_group_ajaxified_multipage_enabled']) || $storage['field_group_ajaxified_multipage_enabled'] !== TRUE) {
    return FALSE;
  }
  $navigation = [];
  $field_groups = $form['#fieldgroups'];
  $multipage = $storage['field_group_ajaxified_multipage_group'];
  $current_step = $storage['field_group_ajaxified_multipage_step']-1;
  $steps = $multipage['children'];

  foreach ($steps as $key => $step) {
    $navigation[$key] = [
      'label' => $field_groups[$step]->label,
      'active' => $key === $current_step,
      'page_done' => $current_step > $key,
    ];
  }

  return $navigation;

}

/**
 * @param $implementations
 * @param $hook
 *
 * @return void
 */
function hel_tpm_editorial_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if (isset($implementations['hel_tpm_editorial'])) {
      $group = $implementations['hel_tpm_editorial'];
      unset($implementations['hel_tpm_editorial']);
      $implementations['hel_tpm_editorial'] = $group;
    }
  }
}
