# Field storage.
field.storage_settings.views_exposed_embed_field:
  type: mapping
  label: Views exposed embed field storage settings
  mapping:
    value:
      type: string
      label: Value

# Field instance.
field.field_settings.views_exposed_embed_field:
  type: mapping
  label: Views exposed embed field settings.

# Default value.
field.value.views_exposed_embed_field:
  type: mapping
  label: Views exposed embed field default value
