<?php

/**
 * @file
 * Provides a contact info entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function hel_tpm_contact_info_theme() {
  return [
    'contact_info' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for contact info templates.
 *
 * Default template: contact-info.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the contact info information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_contact_info(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
