<?php

/**
 * @file
 * Module file for hel_tpm_user_expiry.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_cron().
 */
function hel_tpm_user_expiry_cron() {
  _hel_tpm_user_expire_notification_cron();
}

/**
 * User expire notification cron job.
 */
function _hel_tpm_user_expire_notification_cron() {
  $run_time_limit = strtotime('12 hours', 0);
  $last_run = Drupal::state()->get('hel_tpm_user_expiry.last_run');

  // Run this cron once every 24 hours.
  if ($last_run && (Drupal::time()->getRequestTime() - $last_run) < $run_time_limit) {
    return;
  }

  $limit = strtotime('-3 months -2 weeks');

  // Fetch all users have been inactive for 3 months and 2 weeks.
  $q = Drupal::database()->select('users_field_data', 'ufd')
    ->fields('ufd', ['uid', 'access', 'status'])
    ->condition('uid', 0, '<>')
    ->condition('access', $limit, '<=')
    ->condition('created', $limit, '<=')
    ->condition('status', 1);
  $result = $q->execute()->fetchAll();

  foreach ($result as $user) {
    $queue = Drupal::queue('hel_tpm_user_expiry_user_expiration_notification');
    $queue->createItem($user);
  }

  Drupal::state()->set('hel_tpm_user_expiry.last_run', Drupal::time()->getRequestTime());
}

/**
 * Implements hook_user_login().
 */
function hel_tpm_user_expiry_user_login(UserInterface $account) {
  $state_manager = Drupal::state();
  $state_name = 'hel_tpm_user_expiry.notified.' . $account->id();
  $state = $state_manager->get($state_name);
  // Clear user expiry notification state after user has logged in.
  if (!empty($state)) {
    $state_manager->delete($state_name);
  }
}
