field.widget.settings.hel_tpm_general_inline_entity_form_improved:
  type: mapping
  label: 'Inline entity reference display format settings'
  mapping:
    form_mode:
      type: string
      label: "Form mode"
    override_labels:
      type: boolean
      label: "Override labels"
    label_singular:
      type: label
      label: "Label (singular)"
    label_plural:
      type: label
      label: "Label (plural)"
    allow_new:
      type: boolean
      label: "Allow new"
    allow_existing:
      type: boolean
      label: "Allow existing"
    match_operator:
      type: string
      label: "Match operator"
    allow_duplicate:
      type: boolean
      label: "Allow duplicate"
    collapsible:
      type: boolean
      label: "Collapsible"
    collapsed:
      type: boolean
      label: "Collapsed by default"
    revision:
      type: boolean
      label: "Create new revision"
    content_type_limit:
      type: array
      label: "Content type limit"
