field.widget.settings.hel_tpm_service_dates_service_time_and_place_widget:
  type: mapping
  label: Service time and place widget widget settings
  mapping:
    foo:
      type: string
      label: Foo
