field.widget.settings.hel_tpm_service_dates_service_time_and_place_widget:
  type: mapping
  label: Service time and place widget widget settings
  mapping:
    foo:
      type: string
      label: Foo


# Default value.
field.value.hel_tpm_service_dates_weekday_and_time_field:
  type: mapping
  label: Weekday and times

field.widget.settings.hel_tpm_service_dates_custom_date_and_time_widget:
  type: mapping
  label: Custom Date and Time widget widget settings
