views.field.hel_tpm_file_garbage_collector_report_usages:
  type: views_field
  label: 'File garbage collector usages'

views.area.hel_tpm_file_garbage_collector_report_summary:
  type: views_area
  label: 'File garbage collector summary'
