<?php
namespace Drupal\hel_tpm_general\Plugin\FieTypeExport;

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\entity_export_csv\Plugin\FieldTypeExportBase;

/**
 * Defines paragraph field exporter.
 *
 * @FieldTypeExport(
 *    id = "paragraph_export",
 *    label = @Translation("Paragraph export"),
 *    description = @Translation("Paragraph export"),
 *    weight = 0,
 *    field_type = {
 *      "entity_reference_revisions",
 *    },
 *    entity_type = {},
 *    bundle = {},
 *    field_name = {},
 *    exclusive = FALSE,
 *  )
 */

final class ParagraphExport extends FieldTypeExportBase {
  /**
   * {@inheritdoc}
   */
  public function getSummary() {
    return [
      'message' => [
        '#markup' => $this->t('Paragraph field type exporter.'),
      ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function massageExportPropertyValue(FieldItemInterface $field_item, $property_name, FieldDefinitionInterface $field_definition, $options = []) {
    if ($field_item->isEmpty()) {
      return NULL;
    }
    $configuration = $this->getConfiguration();
    if (empty($configuration['format'])) {
      return $field_item->get($property_name)->getValue();
    }

    $format = $configuration['format'];
    if ($format === 'entity_reference_label') {
      $entity = $field_item->get('entity')->getValue();
      if ($entity instanceof EntityInterface) {
        return $entity->label();
      }
    }

    return $field_item->get($property_name)->getValue();
  }

  public function export(ContentEntityInterface $entity, FieldDefinitionInterface $field_definition, array $options = []) {
    return parent::export($entity, $field_definition, $options); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  protected function getFormatExportOptions(FieldDefinitionInterface $field_definition) {
    $options = parent::getFormatExportOptions($field_definition);
    $options['paragraph_fields'] = $this->t('Paragraph fields');
    return $options;
  }


}