<?php

/**
 * @file
 * Primary module hooks for Hel tpm tmgmt module.
 */

use Drupal\hel_tpm_tmgmt\FieldProcessorMaxwidth;
use Drupal\hel_tpm_tmgmt\LinkFieldProcessorOverride;
use Drupal\tmgmt_content\DefaultFieldProcessor;

/**
 * Implements hook_tmgmt_source_plugin_info_alter().
 */
function hel_tpm_tmgmt_tmgmt_source_plugin_info_alter($info) {
  if (!empty($info['content'])) {
    $info['content']['ui'] = 'Drupal\hel_tpm_tmgmt\ContentEntitySourcePluginUiOverride';
  }
}

/**
 * Implements hook_field_info_alter().
 */
function hel_tpm_tmgmt_field_info_alter(&$info) {
  if (!empty($info['link'])) {
    $info['link']['tmgmt_field_processor'] = LinkFieldProcessorOverride::class;
  }
  foreach ($info as $key => $value) {
    if (empty($value['tmgmt_field_processor'])) {
      continue;
    }
    if ($value['tmgmt_field_processor'] === DefaultFieldProcessor::class) {
      $value['tmgmt_field_processor'] = FieldProcessorMaxwidth::class;
    }
    $info[$key] = $value;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function hel_tpm_tmgmt_entity_type_alter(&$info) {
  if (!empty($info['tmgmt_job_item'])) {
    $content_type = &$info['tmgmt_job_item'];
    $handlers = $content_type->getHandlerClasses();
    $handlers['form']['edit'] = 'Drupal\hel_tpm_tmgmt\Form\HelTpmTmgmtJobItemForm';
    $content_type->setHandlerClass('form', $handlers['form']);
  }
}
